/**
 * AI Advice Routes
 *
 * Accepts transaction summaries and returns personalized financial advice
 * generated by an AI model (Anthropic Claude when an API key is set,
 * smart mock otherwise). The API key lives on the server — never in the
 * mobile app.
 *
 * Environment variables:
 *   ANTHROPIC_API_KEY  — if set, the route calls Claude; otherwise a
 *                        realistic-looking mock is returned for development.
 */

import { FastifyInstance } from 'fastify';
import { aiAdvicePayloadSchema, aiAdviceResponseSchema } from 'shared';
import type { AiAdvicePayload, AiAdviceResponse } from 'shared';

/* ------------------------------------------------------------------ */
/*  AI provider call (Anthropic Claude)                                */
/* ------------------------------------------------------------------ */

async function callClaude(payload: AiAdvicePayload, language?: string): Promise<AiAdviceResponse | null> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return null;

  const systemPrompt = buildSystemPrompt(language);

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-5-20250601',
        max_tokens: 1024,
        system: systemPrompt,
        messages: [
          {
            role: 'user',
            content: `Here is my financial data for this month. Please analyze and give me personalized advice.

Currency: ${payload.currency}
Total Income: ${formatMinor(payload.totalIncomeMinor, payload.currency)}
Total Expenses: ${formatMinor(payload.totalExpenseMinor, payload.currency)}
Daily Average: ${formatMinor(Math.round(payload.dailyAverageMinor), payload.currency)}
Transactions this month: ${payload.transactionCount}
${payload.topCategoryName ? `Top Category: ${payload.topCategoryName} (${payload.topCategoryPercent}% of spending)` : ''}
${payload.prevMonthExpenseMinor ? `Last month's expenses: ${formatMinor(payload.prevMonthExpenseMinor, payload.currency)}` : ''}
${payload.hasBudget ? `Daily Budget: ${formatMinor(payload.dailyBudgetMinor || 0, payload.currency)}` : 'No daily budget set.'}

Category breakdown:
${payload.categoryTotals.map(c =>
  `  - ${c.categoryName}: ${formatMinor(c.totalMinor, payload.currency)}`
).join('\n')}`,
          },
        ],
      }),
    });

    if (!response.ok) {
      console.warn(`Claude API returned ${response.status}`);
      return null;
    }

    const json: any = await response.json();
    const text: string = json.content?.[0]?.text || '';
    return parseAIResponse(text);
  } catch (err) {
    console.warn('Claude API call failed:', err);
    return null;
  }
}

/* ------------------------------------------------------------------ */
/*  System prompt builder                                              */
/* ------------------------------------------------------------------ */

function buildSystemPrompt(language?: string): string {
  const langInstruction = language
    ? `\nIMPORTANT: Respond in the user's language (language code: ${language}). All advice, analysis, and motivation must be written in this language.\n`
    : '';
  return `You are Zeno, a warm, practical financial assistant inside a household account book app. Your job is to look at the user's spending data and give them genuinely useful, personalized advice.${langInstruction}

RULES:
- Be warm and encouraging but honest.
- Always base your advice on the actual numbers provided.
- If the user is doing well, celebrate that.
- If there are warning signs (spending > income, single category dominating), flag them clearly.
- Suggest specific, actionable steps — not generic platitudes.
- Keep advice concise (2-4 sentences per point).

OUTPUT FORMAT — Respond with valid JSON only, using this exact structure:
{
  "analysis": "A 2-3 sentence overall summary of their financial situation this month.",
  "advice": [
    {
      "icon": "one emoji character",
      "title": "Short title (3-6 words)",
      "detail": "2-4 sentences of specific, actionable advice based on their data"
    }
  ],
  "motivation": "One short encouraging sentence to end on."
}

Generate 2-4 advice points. The JSON must be parseable — no markdown fences, no extra text.`;
}

/* ------------------------------------------------------------------ */
/*  Parse AI response into structured data                             */
/* ------------------------------------------------------------------ */

function parseAIResponse(text: string): AiAdviceResponse {
  // Try to extract JSON from the response (handle possible markdown fences)
  const jsonMatch = text.match(/\{[\s\S]*\}/);
  const jsonStr = jsonMatch ? jsonMatch[0] : text;
  try {
    return aiAdviceResponseSchema.parse(JSON.parse(jsonStr));
  } catch {
    console.warn('Failed to parse AI response, falling back to mock');
    return generateMockAdvice({
      totalIncomeMinor: 0,
      totalExpenseMinor: 0,
      currency: 'USD',
      categoryTotals: [],
      dailyAverageMinor: 0,
      transactionCount: 0,
      hasBudget: false,
    });
  }
}

/* ------------------------------------------------------------------ */
/*  Mock advice (development fallback) — still data-driven             */
/* ------------------------------------------------------------------ */

function generateMockAdvice(payload: AiAdvicePayload): AiAdviceResponse {
  const { totalIncomeMinor, totalExpenseMinor, dailyAverageMinor, categoryTotals, topCategoryName, topCategoryPercent, hasBudget, dailyBudgetMinor, prevMonthExpenseMinor, currency } = payload;

  const advice: AiAdviceResponse['advice'] = [];
  const ratio = totalIncomeMinor > 0 ? (totalExpenseMinor / totalIncomeMinor) * 100 : 0;

  // Income health advice
  if (totalIncomeMinor > 0 && totalExpenseMinor > 0) {
    if (ratio > 100) {
      advice.push({
        icon: '🚨',
        title: 'Expenses exceed income',
        detail: `Your spending of ${fmt(totalExpenseMinor, currency)} is ${ratio.toFixed(0)}% of your income. This is unsustainable long-term. Try cutting non-essential categories like dining or entertainment by at least 20% to bring expenses back under control.`,
      });
    } else if (ratio > 70) {
      advice.push({
        icon: '⚠️',
        title: 'Watch your spending ratio',
        detail: `You're using ${ratio.toFixed(0)}% of your income on expenses. Financial experts recommend keeping this under 70% so you have room for savings. Aim to reduce discretionary spending by about 15% this month.`,
      });
    } else {
      advice.push({
        icon: '✅',
        title: 'Healthy income ratio',
        detail: `Great job — your expenses are just ${ratio.toFixed(0)}% of your income. You're in a good position to build savings. Consider putting the surplus into a dedicated savings category each month.`,
      });
    }
  }

  // Top category advice
  if (topCategoryName && topCategoryPercent && topCategoryPercent > 35) {
    advice.push({
      icon: '🎯',
      title: `${topCategoryName} is dominant`,
      detail: `${topCategoryName} makes up ${topCategoryPercent}% of your spending. While it's normal to have a top category, this concentration means a small change here has big impact. Try reducing ${topCategoryName} by just 10% to save ${fmt(Math.round(totalExpenseMinor * 0.1 * topCategoryPercent / 100), currency)} this month.`,
    });
  }

  // Daily spending advice
  if (dailyAverageMinor > 0) {
    const monthlyProjected = Math.round(dailyAverageMinor * 30);
    advice.push({
      icon: '📊',
      title: 'Daily spending pattern',
      detail: `You're spending ${fmt(Math.round(dailyAverageMinor), currency)} per day on average, projecting to ${fmt(monthlyProjected, currency)} this month. ${monthlyProjected > totalExpenseMinor ? 'Tracking higher than your current total, so watch for end-of-month acceleration.' : 'This steady pattern makes budgeting easier — keep it up!'}`,
    });
  }

  // Budget advice
  if (hasBudget && dailyBudgetMinor && dailyBudgetMinor > 0) {
    advice.push({
      icon: '🎯',
      title: 'Daily budget check',
      detail: `Your daily budget is ${fmt(dailyBudgetMinor, currency)}. Staying within this consistently builds great financial discipline. Try the Daily Challenge feature to gamify your progress and earn rewards.`,
    });
  }

  // Savings suggestion
  if (categoryTotals.length > 0) {
    const secondCategory = categoryTotals.length > 1 ? categoryTotals[1] : categoryTotals[0];
    if (secondCategory && secondCategory.totalMinor > 500) {
      const saveAmount = Math.round(secondCategory.totalMinor * 0.15);
      advice.push({
        icon: '🏦',
        title: `Save on ${secondCategory.categoryName}`,
        detail: `Reducing ${secondCategory.categoryName} by just 15% would save you ${fmt(saveAmount, currency)} per month. Look for smaller-cost alternatives or plan ahead to avoid impulse spending in this category.`,
      });
    }
  }

  // Month comparison
  if (prevMonthExpenseMinor && prevMonthExpenseMinor > 0) {
    const change = totalExpenseMinor > 0
      ? Math.round(((totalExpenseMinor - prevMonthExpenseMinor) / prevMonthExpenseMinor) * 100)
      : 0;
    if (change > 10) {
      advice.push({
        icon: '📈',
        title: 'Spending is rising',
        detail: `Your spending is up ${change}% compared to last month. Take a moment to review what changed — was it a one-time expense or a new habit forming? Understanding the why helps you decide what to adjust.`,
      });
    } else if (change < -5) {
      advice.push({
        icon: '📉',
        title: 'Spending is down',
        detail: `Your spending decreased ${Math.abs(change)}% from last month — well done! If this was intentional, you're building great habits. If it happened naturally, use this momentum to set a conscious budget going forward.`,
      });
    }
  }

  // Motivation
  let motivation = '';
  if (totalIncomeMinor > 0 && ratio < 70) {
    motivation = 'You\'re doing a fantastic job managing your money — keep it up!';
  } else if (ratio > 100) {
    motivation = 'Small steps lead to big changes — pick one area to work on this week!';
  } else {
    motivation = 'Every small improvement in your spending habits adds up over time!';
  }

  // Overall analysis
  let analysis = '';
  if (totalExpenseMinor === 0) {
    analysis = 'You haven\'t recorded any expenses this month yet. Start tracking to get personalized insights!';
  } else if (totalIncomeMinor === 0) {
    analysis = `You've spent ${fmt(totalExpenseMinor, currency)} this month across ${categoryTotals.length} categories. Without income data recorded, I can't calculate your savings ratio — add your income for a fuller picture.`;
  } else if (ratio > 100) {
    analysis = `You've spent ${fmt(totalExpenseMinor, currency)} against ${fmt(totalIncomeMinor, currency)} in income this month (${ratio.toFixed(0)}% of income). Your top priorities should be reducing expenses and finding ways to boost your income.`;
  } else if (ratio > 70) {
    analysis = `You're spending ${fmt(totalExpenseMinor, currency)} of your ${fmt(totalIncomeMinor, currency)} income (${ratio.toFixed(0)}%). You're managing OK but there's room to tighten up and build more savings.`;
  } else {
    analysis = `Great shape this month — ${fmt(totalExpenseMinor, currency)} in expenses against ${fmt(totalIncomeMinor, currency)} in income, using just ${ratio.toFixed(0)}% of your income.`;
  }

  return { analysis, advice, motivation };
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

const CURRENCY_SYMBOLS: Record<string, string> = {
  USD: '$', MYR: 'RM', JPY: '¥', EUR: '€', GBP: '£',
  SGD: 'S$', KRW: '₩', THB: '฿', CNY: '¥', INR: '₹',
};

function fmt(amountMinor: number, currency: string): string {
  const amount = Math.abs(amountMinor) / 100;
  const symbol = CURRENCY_SYMBOLS[currency] || currency + ' ';
  const noDecimal = currency === 'JPY' || currency === 'KRW';
  return `${symbol}${noDecimal ? amount.toFixed(0) : amount.toFixed(2)}`;
}

function formatMinor(amount: number, currency: string): string {
  return fmt(amount, currency);
}

/* ------------------------------------------------------------------ */
/*  Route                                                              */
/* ------------------------------------------------------------------ */

export async function aiRoutes(app: FastifyInstance) {
  // Keep old endpoint for backward compatibility
  const { aiMonthlyPayloadSchema: oldPayload, aiInsightResponseSchema } = await import('shared');

  app.post('/ai/monthly-insights', async (request, reply) => {
    const parsed = oldPayload.safeParse(request.body);
    if (!parsed.success) {
      reply.status(400).send({ error: 'Invalid payload', details: parsed.error.format() });
      return;
    }

    const { totalIncomeMinor, totalExpenseMinor, categoryTotals, budgetLimits } = parsed.data;
    const percentageUsed = totalIncomeMinor > 0 ? (totalExpenseMinor / totalIncomeMinor) * 100 : 0;

    const suggestions = [] as { title: string; description: string }[];
    if (percentageUsed > 90) {
      suggestions.push({
        title: 'High spending alert',
        description: `You've used ${percentageUsed.toFixed(1)}% of your income this month. Consider reviewing non-essential expenses.`,
      });
    }
    const topSpending = [...categoryTotals].sort((a, b) => b.totalMinor - a.totalMinor)[0];
    if (topSpending) {
      suggestions.push({
        title: `Top spending: ${topSpending.categoryName}`,
        description: `You spent the most on ${topSpending.categoryName}. Consider setting a stricter budget.`,
      });
    }
    for (const b of budgetLimits) {
      const cat = categoryTotals.find((c) => c.categoryId === b.categoryId);
      if (cat && b.limitMinor > 0 && cat.totalMinor > b.limitMinor) {
        suggestions.push({
          title: 'Over budget',
          description: `Category ${cat.categoryName} exceeded its limit by ${((cat.totalMinor / b.limitMinor - 1) * 100).toFixed(1)}%.`,
        });
      }
    }
    if (suggestions.length === 0) {
      suggestions.push({
        title: 'Great job',
        description: 'Your spending is on track this month. Keep it up!',
      });
    }

    const response = { summary: `Spending: ${totalExpenseMinor} / Income: ${totalIncomeMinor}`, suggestions };
    const parsedResponse = aiInsightResponseSchema.parse(response);
    return { data: parsedResponse };
  });

  // NEW: AI-powered advice endpoint
  app.post('/ai/advice', async (request, reply) => {
    const parsed = aiAdvicePayloadSchema.safeParse(request.body);
    if (!parsed.success) {
      reply.status(400).send({ error: 'Invalid payload', details: parsed.error.format() });
      return;
    }

    const payload = parsed.data;
    const { language } = payload;

    // Try Claude first — it responds in the user's language when told to
    const result = await callClaude(payload, language);

    if (!result) {
      // Don't serve English mock when the user expects a different language.
      // The mobile app has its own localized fallback when we return an error.
      reply.status(503).send({ error: 'AI service unavailable', message: 'AI provider did not respond.' });
      return;
    }

    return { data: result };
  });
}
